sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.11.2
language: python
python:
  - '3.6'
install:
  - sudo docker --version
  - sudo docker-compose --version
script:
    - ./csu ci test_with_coverage
    - ./csu ci test_backwards
    - ./csu ci style
    - ./csu ci docs
deploy:
  script: skip
  deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/dev-deploy.sh
      skip_cleanup: true
      on:
        branch: develop
    - provider: script
      script: bash ./infrastructure/prod-deploy/prod-deploy.sh
      skip_cleanup: true
      on:
        branch: master
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
