sudo: required

services:
  - docker

language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

before_install:
  - docker --version
  - docker-compose --version
  - ./csu start

install:
  - pip3 install -r requirements/test.txt

# Runs test suite
script: flake8

# Stop email notifications but post to organisation Slack channel
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
