version: '3'
services:
  db:
    restart: always
    image: postgres

  web:
    build: .
    command: /bin/bash -c "chmod +x docker-compose-entrypoint.sh && ./docker-compose-entrypoint.sh"
    volumes:
      - ./csunplugged:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
