version: '3'
services:
  postgres:
    restart: always
    image: postgres
    network_mode: host

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    command: /cs-unplugged/csunplugged/docker-development-entrypoint.sh
    volumes:
      - .:/cs-unplugged
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@localhost:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - postgres
    network_mode: host

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./csunplugged/:/app/
      - /app/node_modules
    depends_on:
      - django
    network_mode: host
