version: '3'
services:
  postgres:
    restart: always
    image: postgres

  django:
    build:
      context: .
      dockerfile: ./csunplugged/Dockerfile
    command: /bin/bash -c "chmod +x docker-compose-entrypoint.sh && ./docker-compose-entrypoint.sh"
    volumes:
      - ./csunplugged:/code
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    expose:
      - "8080"
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - ./csunplugged/:/app/
      - /app/node_modules
    depends_on:
      - django
    ports:
      - "80:80"
