version: '3'
services:
  postgres:
    restart: always
    image: postgres

  csu-django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    image: uccser/csu-django:local-2.0.0-alpha.4
    command: /cs-unplugged/csunplugged/docker-development-entrypoint.sh
    volumes:
      - .:/cs-unplugged
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - postgres

  csu-nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    image: uccser/csu-nginx:1.0.1
    volumes:
      - ./csunplugged/:/app/
      - /app/node_modules
    depends_on:
      - csu-django
    ports:
      - "80:80"
