runtime: custom
env: flex

beta_settings:
    cloud_sql_instances: ${GOOGLE_CLOUD_SQL_CONNECTION_NAME}

env_variables:
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  GOOGLE_CLOUD_SQL_DATABASE_USERNAME: ${GOOGLE_CLOUD_SQL_DATABASE_USERNAME}
  GOOGLE_CLOUD_SQL_DATABASE_PASSWORD: ${GOOGLE_CLOUD_SQL_DATABASE_PASSWORD}
  GOOGLE_CLOUD_SQL_CONNECTION_NAME: ${GOOGLE_CLOUD_SQL_CONNECTION_NAME}
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: cs-unplugged-dev.appspot.com

manual_scaling:
  instances: 1
